### ISSUE TITLE
Pictures bug on android

### ISSUE THREAD

**Issue by Sydyney** [friedrich-de/Basic-Mining-Deck#1]

**Comment by friedrich-de** [comment]
Hi, I see you deleted your issue. I assume you saw the description on how to restore images in the README but there is indeed an issue with the spacing of hidden images. The hidden images should not take up any space. I'll look into it.

**Comment by Sydyney** [comment]
> Hi, I see you deleted your issue. I assume you saw the description on how to restore images in the README but there is indeed an issue with the spacing of hidden images. The hidden images should not take up any space. I'll look into it.

Yes, sorry I didn't read the description correctly.

**Comment by friedrich-de** [comment]
Alright, I was able to reproduce the issue but ONLY in the AnkiDroid preview screen. In actual reviews the card displayed correctly. I assume it's a bug with the AnkiDroid preview function not correctly handling hidden elements. The card template seems to be alright. You already discovered how to restore images too so I assume this is solved.

![mobile_card](https://user-images.githubusercontent.com/59431934/222750953-025a9ffb-70d8-4dfd-b8f1-ae34060eb28f.jpeg)
