### ISSUE TITLE
render error

### ISSUE THREAD

**Issue by kuriroley** [friedrich-de/Basic-Mining-Deck#3]
When making new cards I have the following problem
{pitch-accent-graphs-render-error}
ふる
{glossary-no-dictionary-render-error}
{clipboard-text-render-error}

how I can I fix it?

Cheers 

![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/87399315/98bde2d4-9e65-4c84-ac4e-18764ce9c143)

**Comment by friedrich-de** [comment]
Do you have dictionaries installed including the pitch accent one? Did you reset your handlebars? Does the Yomichan preview correctly show content for the fields?

**Comment by imsamuka** [comment]
Which browser are @kuriroley using? I'm using Firefox and I also have these problems, which i think is because of discrepancies on Yomichan version for each browser

**Comment by kuriroley** [comment]
> Which browser are @kuriroley using? I'm using Firefox and I also have these problems, which i think is because of discrepancies on Yomichan version for each browser

I was using Firefox too... I did not solve the problem, I just started doing a simpler way of saving words and meanings...

**Comment by anprowh** [comment]
I had this problem, when I was using Yomichan with Firefox (but only with {pitch-accent-graphs-render-error}), now I use Yomibaba and it works fine.

**Comment by friedrich-de** [comment]
Just tried with the newest version of Yomitan and it works fine. Seems the issue was with the outdated version of Yomichan on Firefox.
