### ISSUE TITLE
Support for swiping on ankidroid?

### ISSUE THREAD

**Issue by doctorhibert** [friedrich-de/Basic-Mining-Deck#6]
I'm not entirely sure why, but when trying to swipe left in ankidroid, you need to swipe twice, as shown below (please ignore the older cards with no image):

![mpv_adjC8YKXaM](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/299b538c-ce6c-4e4a-b492-c29917b11137)

Is it because of the size of the cards or something? Is there a way to fix this, be it in the css or on ankidroid somehow?

**Comment by friedrich-de** [comment]
Yes, looks like it's because of the size. The issue seems to be that the card is bigger than your screen, resulting in scroll able space to the side. 

You can reduce the max-width property in the styling section for the portrait orientation to 90% or 80%. Should fix this.
